services:
  site:
    build:
      context: .
      target: site
    restart: "always"
    environment:
      DEBUG: false
      FULLCHAIN_PATH: "/cert/fullchain.pem"
      PRIVKEY_PATH: "/cert/privkey.pem"
    volumes:
      - ${FULLCHAIN_PATH}:/cert/fullchain.pem
      - ${PRIVKEY_PATH}:/cert/privkey.pem
    network_mode: "host"
